---
title: "Syllabus"
output:
  html_document:
    toc: yes
    toc_depth: 1
    toc_float:
      collapsed: no
---

<style>
h1{font-weight: 400;}
</style>

# Basic information {#basicinfo}

* **Course title:** SDS/MTH 220: Introduction to Probability and Statistics
* **Instructor:** [Albert Y. Kim](https://rudeboybert.rbind.io/) - Assistant Professor of Statistical & Data Sciences
* **~~Email:~~ Slack team**: Click hashtag icon in navbar for the browser interface or use the [desktop app](https://slack.com/downloads/){target="_blank"}.
    + I will respond to Slack messages within 24h, but not during weekends.
    + If possible, please only Slack me with briefer and administrative questions; I prefer having more substantive conversations in person.
* **Meeting locations/times:** 
    + **Lectures**: Sec 03: MWF 1:10-2:30 - Sabin-Reed 301
    + **Labs**: Held by Dr. Jenny Smetzer
        + Sec 05: Tu 9:00-10:20 - Sabin-Reed 301
        + Sec 06: Th 9:00-10:20 - Sabin-Reed 301
* **Outside help**:
    + Albert's office hours: M & Tu 3-6pm or by appointment - McConnell Hall 215
    + Jenny's office hours: [Book here](https://jennysmetzer.youcanbook.me/{target="_blank"} - Bass 403
    + [Spinelli Center for Quantitative Learning](https://www.smith.edu/qlc/){target="_blank"}
        1. [Tutoring](https://www.smith.edu/qlc/tutoring.html?colStats=open#PanelStats){target="_blank"}: Sunday thru Thursday 7-9pm - McConnell Hall 301.
        1. [Data Counselor Raul Zelada Aprili](https://www.smith.edu/qlc/tutoring.html?colDataCnslr=open#PanelDataCnslr){target="_blank"}: By appointment - Spinelli Center.

## Expectations

* **Slack**:
    + You are expected to stay on top of announcements and
direct messages in Slack. For strategies that suit you and your work style (ex: turning on email notifications), please don't hesistate to ask me for suggestions!
    + I will respond to Slack messages within 24h, but will respond to weekend messages (Friday afternoon to Monday morning) at my discretion.
    + If possible, please only Slack me with briefer and administrative questions; I prefer having more substantive conversations in person. 
* **Lectures**:
    + You do not need to inform me of *occasional* absenses.
However, you are responsible for asking your peers for what you missed. For
example, makeup lectures will not be held during office hours.
    + You are expected to bring your fully charged laptop, a set of headphones, colored pens/pencils, and your paper notebook to every lecture.


***


    
# Course Description & Objectives

* **Official course description**: On [Smith College
Course Search](https://www.smith.edu/academics/academic-program/curriculum/course-search?term=Fall+2018&dept=Statistical+and+Data+Sciences&instr=Albert+Y.+Kim&credits=&course_numb=220&course_keywd=&op=Submit&form_build_id=form-aR3I9kjnzv-y9YC5iG9EZdxZg_0shLeVcJPIoLE9ABM&form_id=campus_course_search_basic_search_form){target="_blank"}.
* **Objectives** (<a target="_blank" class="page-link" href="static/syllabus_slides.html">slides</a>): This semester you will
    1. Learn statistical inference through data science, not mathematics/probability theory.
    1. Engage in the data/science research pipeline in as faithful a manner as possible while maintaining a level suitable for novices.
    1. Develop your statistical literacy, a necessary ability for effective citizenship.



***



# Topic Schedule and Readings {#topicschedule}

A rough topic schedule and corresponding readings are posted below and on the [main](index.html) page. We will draw from the following sources:

1. ["ModernDive: An Introduction to Statistical and Data Sciences via R (MD)"](https://moderndive.netlify.com/){target="_blank"} by Ismay and Kim (click link in menubar above).
1. ["OpenIntro: Introductory Statistics with Randomization and Simulation (OI)"](https://www.openintro.org/stat/textbook.php?stat_book=isrs/){target="_blank"} by Diez, Barr, and Cetinkaya-Rundel
    + Free [PDF](https://www.openintro.org/download.php?file=isrs1_tablet&referrer=/stat/textbook.php){target="_blank"}
    + Hardcopy. Available for $8.49 on [Amazon](https://www.amazon.com/Introductory-Statistics-Randomization-Simulation-David/dp/1500576697/ref=pd_sbs_14_2?_encoding=UTF8&pd_rd_i=1500576697&pd_rd_r=8a25adfe-b61a-11e8-8e51-357518f34f72&pd_rd_w=SqIFV&pd_rd_wg=mb7dk&pf_rd_i=desktop-dp-sims&pf_rd_m=ATVPDKIKX0DER&pf_rd_p=53dead45-2b3d-4b73-bafb-fe26a7f14aac&pf_rd_r=83CCQTHW3KV5NTNHT22J&pf_rd_s=desktop-dp-sims&pf_rd_t=40701&psc=1&refRID=83CCQTHW3KV5NTNHT22J){target="_blank"}
1. DataCamp: an online interactive environment for learning data science currently via R and Python. On top of the DataCamp courses we'll cover this semester, you have free access to [all their courses](https://www.datacamp.com/courses/all){target="_blank"} for 6 months. 

<iframe src="https://docs.google.com/spreadsheets/d/e/2PACX-1vQM-5FVt5BKJZsfElEV19NwD2MXGgSVUfGLB7dUoD0MbCU6Dkzqx66UMxbgqMaiS6H8CP8numV5Xaf-/pubhtml?gid=1373353942&single=true&amp;widget=true&amp;headers=false" width="100%" height="300"></iframe>

## Expectations

* **Topics**: Note the topic schedule may shift depending on class progress. That being said, I will try to keep the schedule up-to-date for at least the upcoming two lectures.
* **Readings**:
    + You are not required to cover readings for any given lecture beforehand as you'll be given class time to do so in the presence of your peers. However, if you feel you would benefit from reading beforehand, please feel free!
    + You are however responsible for finishing the readings before the start of the next lecture.
* **Reference**: These are optional reference readings if you would like a second perspective on the readings. For example, say you would like a second persepective on "histograms" on top of what we covered in ModernDive, I suggest reading any sections related to "histograms" in Open Inro Chapter 3 as needed, not the entire chapter.
* **DataCamp**: See [DataCamp Assignments](#datacamp) below.
* **Important Events**: Please be sure to frequently check the far-right column for important deadlines and events.



***  



# Evaluation

## Weekly Problem Sets 10%

* The problem sets in this class should be viewed as low-stakes opportunities to
practice, instead of evaluative tools used by the instructor to assign grades.
* Assigned/due on Wednesdays.


## DataCamp Assignments 10% {#datacamp}

* Assigned/due on Wednesdays.
* Expectations:
    1. DataCamp is meant to be low stakes-practice, so the only thing that matters for your grade is whether you complete the course. So while things like the number of hints/solutions taken don't factor into your grade, it is important to make a good faith effort to answer these questions the best you can.
    1. Taking notes based on what you cover is not required, but please do so if you feel you will benefit. 
    1. I *expect* most people to take no more than 4 hours per DataCamp assignment.
    1. Please note retention of the material will not be perfect the first time through. The only way to really retain the material is via lots of practice/doing. For now, think of this as a introduction.
    1. You do not need to complete any DataCamp courses in preparation for future lectures; they will always be explicitly assigned and you will subsequently be given time during Tu/Th lab sections to do them. 


## Quizzes 5%

There will be 2-3 quizzes assigned during the course of the semester. They will always be announced the lecture before. 

## Term Project 25% {#termproject}

See [Term Project](term_project.html) page.

## Three Midterms: 45%

* There will be three self-scheduled midterms in the library. They are closed-book:
    1. Open on Friday 9/28 at 5pm, ends on Sunday 9/30 evening (Time TBD)
    2. Open on Friday 11/2 at 5pm, ends on Sunday 11/4 evening (Time TBD)
    3. Open on Friday 11/30 at 5pm, ends on Sunday 12/2 evening (Time TBD)

## Engagement 5% {#engagement}

It is difficult to explicit codify what constitutes "an engaged student," so 
instead I present the following rough principle I will follow: *you'll only get
out of this class as much as you put in*. Some examples of behavior counter to
this principle:

* Not participating in class.
* Engaging so little with me, either in class or during office hours, that I
don't know what your voice sounds like.
* Shirking group work.
* [Ghosting](https://www.urbandictionary.com/define.php?term=Ghosting&utm_source=search-action){target="_blank"}.
* Doing the bare minimum to get by. 


## Expectations {#evaluation-expectations}

1. **Collaboration**: While I encourage you to work with your peers for problem
sets and labs, you must submit your own answers and not simple rewordings of
another's work. Furthermore, all collaborations must be explicitly acknowledged
in your submissions.
1. **Honor Code**: All your work must follow the [Smith College Academic Honor
Code
Statement](https://www.smith.edu/sao/handbook/socialconduct/honorcode.php){target="_blank"};
in particular all external sources must be cited in your submissions.



***



# Accommodations {#accommodations}
 
Smith is committed to providing support services and reasonable accommodations to all students with disabilities. To request an accommodation, please register with the Disability Services Office at the beginning of the semester. To do so, call 413.585.2071 to arrange an appointment with Laura Rauscher, Director of Disability Services.

## Expectations

If you require accommodations, please provide me with documentation
and advance notice for when you think you will need them.



***



# Code of Conduct {#codeofconduct}

As the instructor and assistants for this course, we are committed to making
participation in this course a harassment-free experience for everyone,
regardless of level of experience, gender, gender identity and expression,
sexual orientation, disability, personal appearance, body size, race, ethnicity,
age, or religion. Examples of unacceptable behavior by participants in this
course include the use of sexual language or imagery, derogatory comments or
personal attacks, trolling, public or private harassment, insults, or other
unprofessional conduct.

As the instructor and assistants we have the right and responsibility to point
out and stop behavior that is not aligned to this Code of Conduct. Participants
who do not follow the Code of Conduct may be reprimanded for such behavior.
Instances of abusive, harassing, or otherwise unacceptable behavior may be
reported by contacting the instructor.

This Code of Conduct is adapted from the [Contributor
Covenant](http://contributor-covenant.org){target="_blank"}, version 1.0.0,
available [here](http://contributor-covenant.org/version/1/0/0/){target="_blank"}.

## Expectations

All students, the instructor, and all assistants are expected to adhere to this
Code of Conduct in all settings: lectures, office hours, during tutoring hours,
and over Slack.
