---
title: "STAT/MATH 135 Syllabus"
author: "Albert Y. Kim"
date: "`r Sys.Date()`"
output: pdf_document
---

<style>
h1{font-weight: 400;}
</style>

# Basic information {#basicinfo}

* **Course title:** STAT/MATH 135 - Introduction to Statistics via Modeling
* **Instructor:** [Albert Y. Kim](https://rudeboybert.rbind.io/) - Lecturer of
Statistics
* **~~Email:~~ Slack team**: <a target="_blank" class="page-link"
href="https://stat135-spring-2018.slack.com/">stat135-spring-2018.slack.com</a> (click hashtag icon in navbar)
* **Meeting locations/times:**
    + **Lectures**: In Merrill Science Center 131
        + Sec 02: M 9:00-9:50 and Tu/Th 8:30-12:50
        + Sec 03: M 10:00-10:50 and Tu/Th 10:00-11:20
        + Sec 04: M 1:00-1:50 and Tu/Th 1:00-2:20
    + **Outside help**:
        + Albert's office hours: M 3:00-5:00 and Th 3:00-5:00 in Seeley Mudd
        208, or by appointment.
        + Drop-in tutoring at Moss Q-Center: Sunday thru Thursday 7pm-9pm in
        Merrill Science Center 300B.



***


    
# Course Description & Objectives

* **Official course description**: On [Amherst College
Webpage](https://www.amherst.edu/academiclife/departments/courses/1718F/STAT/STAT-135-1718F).
* **Objectives** (<a target="_blank" class="page-link" href="static/syllabus_slides.html">slides</a>): This semester you will
    1. Engage in the data/science research pipeline in as faithful a manner as possible while maintaining a level suitable for novices.
    1. Develop the toolbox necessary to "think with data":  data science, data modeling, and statistical inference.
    1. Take your first steps coding.
    1. Develop your statistical literacy, a necessary ability for effective citizenship.



***



# Materials

We will draw on three chief sources:

1. "Stats: Data and Models" (4th Edition) by De Veaux, Velleman, and Bock.
1. "ModernDive: An Introduction to Statistical and Data Sciences via R" by Ismay and Kim (link in the navigational bar above).
1. DataCamp: an online interactive environment for learning data science currently via R and Python. On top of the DataCamp courses we'll cover this semester, you have free access to [all their courses](https://www.datacamp.com/courses). 




***  



# Expectations

As a student in this class:

1. Communication:
    a) You are expected to stay on top of announcements and direct messages in Slack.
    a) You can expect responses to Slack messages from me within 24h, but not
    during weekends.
    a) Please ask only administrative and briefer questions on Slack, as I prefer 
    having more substantive conversations in person.
1. Lectures:
    a) You are expected to bring your laptop to every lecture.
    a) You are not required to inform me of occasional absenses. However, you are
    resposible for asking your peers, and not the instructor, for what you missed.
1. Problem sets:
    a) All problem sets must be handed in on time in lecture; no extensions will
    be granted.
    a) For written homeworks, you are expected to hand in a physical copy that
    is stapled and has the fringe/perf from any spiral notebook paper removed.
    If you can't make lecture, ask peer to hand it in for you.
    a) You must show all your work explain your reasoning in your solutions. 
    a) Collaboration: While I encourage you to discuss problem sets with your
    peers, you must submit your own answers and not simple rewordings of
    another's work. Furthermore, as per the Amherst College Student Code of
    Conduct's statement on [intellectual responbisility and
    plagiarism](https://www.amherst.edu/offices/student-affairs/community-standards/intellectual-responsibility-and-plagiarism)
    all collaborations must be explicitly acknowledged in your submissions.
1. Exams: 
    a) There will be no make-up nor rescheduled midterms, except in the
    following cases if documentation (such as a dean's note) is provided:
    serious illness, death in the family, athletic commitments, religious
    obligations, and job interviews.
    a) If you require special testing accommodations, you must inform me over Slack at least a week in advance. 
1. Final project: You must cite all your sources and follow the Amherst College
Student Code of Conduct's statement on intellectual responbisility and
plagiarism linked above.    
   
    
***



# Evaluation


## Weekly Problem Sets 10%

The problem sets in this class should be viewed as low-stakes opportunities to
practice, instead of evaluative tools used by the instructor to assign grades.

* Assigned/due on Tuesdays.
* No extensions for problem sets will be granted.
* Assignments will be graded on the following qualitative scale:
    1. Check-: You unfortunately struggled on this problem set and
    should go to office hours or to the tutoring center.
    1. Check: This is typically the most common grade. You did everything mostly well and there are no red flags. However,
    you should still compare your work to the posted solutions.
    1. Check+: You went above and beyond what was required and "wowed" us.
* Lowest two scores dropped.
* Translation to final grade: If you earn Checks for all problem sets, you can expect roughly 8% out of 10%. 


## Term Project 25% {#termproject}

See [Term Project](term_project.html) page.

## Exams: 55%

* Breakdown: 15% for each midterm and 25% for the final
* All exams are cummulative.
* There will be no extra-credit work to improve exam scores after the fact.

## Engagement 10% {#engagement}

It is difficult to explicit codify what constitutes "an engaged student," so 
instead I present the following rough principle I will follow: *you'll only get
out of this class as much as you put in*. Some examples of behavior counter to
this principle:

* Not participating in in-class exercises.
* Engaging so little with me, either in class or during office hours, that I
don't know what your voice sounds like.
* Doing the bare minimum to get by. 



***


# Inclusion and Accessibility
 
I strive to make this course welcoming to all students. If you would like to
discuss your learning needs with me, please schedule a meeting. I look forward
to working with you to understand and support your academic success.
 
In particular, if you have a documented disability that requires accommodations,
you will need to register with Accessibility Services for coordination of your
academic accommodations. You can reach them via email at
<accessibility@amherst.edu>, or via phone at 413.542.2337. Once you have your
accommodations in place, I will be glad to meet with you privately during my
office hours or at another agreed upon time to discuss the best implementation
of your accommodations.



***

\vspace{12pt}

Name and section number:  

\vspace{12pt}

Signature:

\vspace{12pt}

Date: 

\vspace{12pt}


Please staple this document before submitting.
